name: IEM Git Sync

on: [push, delete]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://git.iem.at/fshstk/clickr.git
          target-username: ${{ secrets.IEM_USER }}
          target-token: ${{ secrets.IEM_TOKEN }}
